# Generated by Django 3.2.18 on 2023-07-06 09:43
from django.db import migrations
from saleor.discount.tasks import SaleToPromotionConverter


def run_migration(_apps, _schema_editor):
    SaleToPromotionConverter.convert_sales_to_promotions()


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0048_promotiontranslation"),
    ]

    operations = [migrations.RunPython(run_migration, migrations.RunPython.noop)]
